pipeline:
  identifier: Build_markdown_1743502688554
  name: Build markdown
  orgIdentifier: default
  projectIdentifier: Harness_project
  properties:
    ci:
      codebase:
        connectorRef: org.GithubConnection
        repoName: markdown
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: false
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          buildIntelligence:
            enabled: false
        type: CI
        description: ""
